# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: FOI უსაფრთხოება
repo_url: https://github.com/foige/security.foi.ge
repo_name: ""
markdown_extensions:
  - attr_list
  - abbr
  - md_in_html
  - tables
  - pymdownx.blocks.details
  - pymdownx.arithmatex
  - pymdownx.blocks.admonition
  - pymdownx.keys
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.blocks.tab:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      slugify: !!python/name:pymdownx.slugs.uslugify
      permalink: true
      toc_depth: 4
plugins:
  - material-plausible
  - include-markdown
  - search
  - privacy
  - minify
  - social
extra:
  generator: false
extra_css:
  - assets/stylesheets/extra.css?v=1724224182
theme:
  name: material
  font:
    text: Noto Sans Georgian
  palette:
    scheme: slate
  custom_dir: theme
  favicon: assets/brand/images/logo-32x32.png
  logo: assets/brand/images/logo.png
  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.indexes
    - content.action.edit
    - content.tabs.link
    - content.tooltips
    - search.highlight
    - content.code.copy
nav:
  - მთავარი: index.md
#  - გიდი:
#      - guide/prerequisites.md
  - გადაწყვეტები:
      - solutions/index.md
      - "საბაზისო":
          - solutions/passwords.md
          - solutions/mfa.md
      - "ოპერაციული სისტემები":
          - solutions/windows.md
          - solutions/macos.md
          - solutions/ios.md
          - solutions/android.md
      - "რეკომენდაციები":
          - solutions/messaging.md
          - solutions/dns.md
          - solutions/vpn.md
          - solutions/antivirus.md
      - "საფრთხეები":
          - solutions/misconceptions.md
          - solutions/behavior.md
          - solutions/hardware-keys.md
  - FOI Security Policy:
      - policies/index.md
      - "ინსტალაცია და პარამეტრები":
          - "Windows": policies/windows.md
          - "macOS": policies/macos.md
          - "iOS": policies/ios.md
          - "ბრაუზერები": policies/browser.md
  - FOI პაროლების გენერატორი:
      - tools/password-generator.md
  - "FOI-ს შესახებ":
      - about/index.md
      - about/tos.md
      - about/privacy.md
      - about/trainers.md