#!/bin/bash
SCRIPT_URL="https://raw.githubusercontent.com/foige/security/main/docs/policies/files/apple/foi_tools.sh"

timestamp=$(date +%Y%m%d%H%M%S)
temp_script="/tmp/foi_tools_${timestamp}.sh"

curl -s "$SCRIPT_URL" -o "$temp_script"
chmod +x "$temp_script"
bash "$temp_script"

rm "$temp_script"